version: '3'
services:
  # ローカルRedisコンテナ
  redis_cluster:
    image: "redis:latest"
    hostname: "redis_cluster"
    container_name: redis_cluster
    volumes:
      - "./redis_data:/data"
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
    networks:
      local_aws:

  # ローカルaws
  local_aws:
    container_name: local_aws
    image: localstack/localstack
    environment:
      - SERVICES=s3, dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./aws_data/localstack}:/tmp/localstack"
    ports:
      - "4569:4569" # DynamoDB
      - "4572:4572" # S3
      - "9000:8080" # ダッシュボードへの接続ポート
    networks:
      local_aws:
networks:
  local_aws:
    driver: bridge